export const TXT_SEARCH_BAR_PLACEHOLDER = '¿Qué estás buscando?'
export const TXT_BUTTON_LEGAL = 'Ver Información Legal'
export const TXT_HOME_LOGO_ALT = 'Lider.cl #JuntosNosCuidamos'
export const TXT_BUTTON_FILTER = 'Ordernar por: '
export const TXT_BUTTON_MENU = 'Categorías'
export const TXT_BUTTON_SUPERMARKET = 'Supermercado'